name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Use Volta
        uses: volta-cli/action@v1

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: add CNAME
        run: echo 'booklet2024.huling.org' >> ./dist/webpub/CNAME

      - name: Deploy webpub
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/webpub

      - name: Archive pdf
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/output.pdf
